#programa tabuada, é o inicio do meu aprendizado por isso só consegui fazer dessa forma.
tab = int(input('Digite um numero para saber a tabuada:'))
print ('-' * 10)
print('{} x {} = {}'.format(tab, 1, tab*1))
print('{} x {} = {}'.format(tab, 2, tab*2))
print('{} x {} = {}'.format(tab, 3, tab*3))
print('{} x {} = {}'.format(tab, 4, tab*4))
print('{} x {} = {}'.format(tab, 5, tab*5))
print('{} x {} = {}'.format(tab, 6, tab*6))
print('{} x {} = {}'.format(tab, 7, tab*7))
print('{} x {} = {}'.format(tab, 8, tab*8))
print('{} x {} = {}'.format(tab, 9, tab*9))
print('{} x {} = {}'.format(tab, 10, tab*10))
print ('-' * 10)
